# the BioSample accession
biosample_accession: SAMN16850904

# name of CSV file listing barcode runs to upload
barcode_runs: ../data/barcode_runs.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/jbloom_fhcrc.org_IuMBgK44

# Meaningful name for this sample's FTP folder:
ftp_subfolder: clinical_Abs_barcodes
